Add Button chaser (Normal)
MarcRaeder/Button-Chaser pull request #1
Opened 2022-09-05 13:24 UTC by MarcRaeder

Add Button-Chaser without Bonus-tasks

2022-09-05 15:26 UTC, stefanluth requested changes

2022-09-05 15:26 UTC, stefanluth commented on button-chaser.css
> +}
I believe .css files should be indented with 2 whitespaces, not 4.

2022-09-06 07:23 UTC, stefanluth requested changes

2022-09-06 07:23 UTC, stefanluth commented on .vscode/settings.json
> +}
Remove :)

2022-09-06 07:23 UTC, stefanluth commented on button-chaser.js
> +button = document.getElementsByClassName("button-container")[0];
```suggestion
const button = document.getElementsByClassName("button-container")[0];
```

2022-09-06 07:23 UTC, stefanluth commented on button-chaser.js
> +    }
You could move function outside the moveButton function.

2022-09-06 13:37 UTC, stefanluth commented
I believe these (literal) edge cases should behave differently, no?

https://user-images.githubusercontent.com/80166473/188649086-4f9fc17c-8a57-476f-8907-f97bfd45ad00.mov


https://user-images.githubusercontent.com/80166473/188649308-7ff37e88-7f5e-407b-b5c6-a95518e75f79.mov

I would expect the button to go away from the edge, if my cursor is coming from there.

2022-09-07 12:12 UTC, stefanluth commented on button-chaser.html
> +</html>
Two spaces indents :)

2022-09-07 12:12 UTC, stefanluth commented on button-chaser.js
> +    const mousePositionX = event.x;
Two spaces indents :)

2022-09-07 12:36 UTC, stefanluth approved these changes

2022-09-07 12:37 UTC, MKrips approved these changes

2022-09-07 12:37 UTC, merged