Button chaser special (Vector Solution)
MarcRaeder/Button-Chaser pull request #2
Opened 2022-09-07 12:02 UTC by MarcRaeder

Add Button-Chaser with Vector Solution

2022-09-08 12:36 UTC, stefanluth requested changes

2022-09-08 12:36 UTC, stefanluth commented on button-chaser-vector.js
> +  button.style.left = `${document.body.offsetWidth / 2}px`;
```suggestion
function fromCornerToMid() {
  button.style.left = `${document.body.offsetWidth / 2}px`;
```

2022-09-08 12:36 UTC, stefanluth commented on button-chaser-vector.js
> +  }
Move conditions to variables :)

2022-09-08 12:36 UTC, stefanluth commented on button-chaser-vector.js
> +const projectcontainer = document.getElementsByClassName("project-container")[0];
```suggestion
const projectContainer = document.getElementsByClassName("project-container")[0];
```

2022-09-09 06:12 UTC, DevBastiS requested changes

2022-09-09 06:12 UTC, DevBastiS commented on button-chaser-vector.js
> +  var dX = e.clientX - buttonX;
what is d?

2022-09-09 06:12 UTC, DevBastiS commented on button-chaser-vector.js
> +  var distance = Math.sqrt(Math.pow(dX, 2) + Math.pow(dY, 2));
distance from what?

2022-09-09 06:12 UTC, DevBastiS commented on button-chaser-vector.js
> +  }
```suggestion
  }
  
```

2022-09-09 06:12 UTC, DevBastiS commented on button-chaser-vector.js
> +  }
What @stefanluth says

2022-09-09 14:12 UTC, stefanluth approved these changes

2022-09-13 07:30 UTC, DevBastiS approved these changes

2022-09-13 07:30 UTC, DevBastiS commented on button-chaser-vector.js
> +  let buttonIsInBottomRightCorner = buttonRightSide >= (projectContainer.offsetWidth - xBorder) && button.offsetTop >= (projectContainer.offsetHeight - yBorder);
```suggestion
  var buttonX = button.offsetLeft + (button.offsetWidth / 2);
  var buttonY = button.offsetTop + (button.offsetHeight / 2);
  
  var VectorXpositionMouseToButton = e.clientX - buttonX;
  var VectorYpositionMouseToButton = e.clientY - buttonY;
  
  var distanceMouseToButton = Math.sqrt(Math.pow(VectorXpositionMouseToButton, 2) + Math.pow(VectorYpositionMouseToButton, 2));
  
  var buttonRightSide = button.offsetLeft + button.offsetWidth;
  
  let buttonIsInTopLeftCorner = button.offsetLeft <= xBorder && button.offsetTop <= yBorder;
  let buttonIsInBottomLeftCorner = button.offsetLeft <= xBorder && button.offsetTop >= (projectContainer.offsetHeight - yBorder);
  let buttonIsInTopRightCorner = buttonRightSide >= (projectContainer.offsetWidth - xBorder) && button.offsetTop <= yBorder;
  let buttonIsInBottomRightCorner = buttonRightSide >= (projectContainer.offsetWidth - xBorder) && button.offsetTop >= (projectContainer.offsetHeight - yBorder);
```

2022-09-13 13:04 UTC, stefanluth commented on button-chaser-vector.js
> +  let buttonIsInBottomRightCorner = buttonRightSide >= (projectContainer.offsetWidth - xBorder) && button.offsetTop >= (projectContainer.offsetHeight - yBorder);
```
    var x = projectContainer.offsetHeight - yBorder;
```

Extract some of the calculations into variables (with proper names) to improve readability :)

2022-09-27 14:19 UTC, DevBastiS commented
What Stefan said

2022-10-05 06:27 UTC, merged